services:
  - type: web
    name: cloudbox-server
    env: node
    plan: free
    region: oregon
    buildCommand: pnpm i --frozen-lockfile && pnpm --filter cloudbox-server build
    startCommand: pnpm --filter cloudbox-server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://cloudbox-web.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENC_SECRET
        sync: false
      - key: ENC_IV
        sync: false
      - key: STORAGE_QUOTA_MB
        value: "10240"
  - type: web
    name: cloudbox-web
    env: static
    buildCommand: pnpm i --frozen-lockfile && pnpm --filter cloudbox-web build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://cloudbox-server.onrender.com/api
